// const getCertificate = () => {
//     try {
//         return window.getSelectedCertificate().certificateBlob;
//     } catch (e) {
//         console.log('Error: ', e);
//         notification.error({
//             message: 'Вставьте карту',
//         });
//     }
// };

const getCertificate = () => {
    return 'MIIENTCCA52gAwIBAgIgCdjOfK9D6S3+bK8QJaZFc0fvxXN73gzxna4aUTXFUKAwDgYKKwYBBAG1EQECBwUAMIGIMUEwPwYDVQQDEzhTdGF0ZSBTZWN1cml0eSBTZXJ2aWNlIG9mIFJlcHVibGljIEthemFraHN0YW4gUHJpbWFyeSBDQTE2MDQGA1UEChMtU3RhdGUgU2VjdXJpdHkgU2VydmljZSBvZiBSZXB1YmxpYyBLYXpha2hzdGFuMQswCQYDVQQGEwJLWjAeFw0yMTEyMjAwNTE0MDNaFw0yNDEyMTkwNTE5MDNaMIHZMQswCQYDVQQGEwJLWjEcMBoGA1UEBwwT0J3Rg9GALdCh0YPQu9GC0LDQvTE2MDQGA1UEChMtU3RhdGUgU2VjdXJpdHkgU2VydmljZSBvZiBSZXB1YmxpYyBLYXpha2hzdGFuMRUwEwYDVQQLEww5OTA0MDM0NTAzNTUxOTA3BgNVBAMMMNCU0LDRg9C80LHQsNC10LLQsCDQodCw0LzQsNC7INCh0LXRgNGW0LrSm9GL0LfRizEiMCAGCSqGSIb3DQEJARYTU19EYXVtYmF5ZXZhQHNnby5rejCBpDAOBgorBgEEAbURAQURBQADgZEABgIAAEyqAAAARUMxAAQAAEsT0BI0c2ChDOPsfjTkwe8oKHTqmnZTcGO04Myi6/qBm0f32tgvwC6piyJzN0rsDkStuikzI3+mYSbwj90J8USyHSSUBB74K+rfvKqDRzxubgKsDPuGzqfoQH3UNk9VV2BMRea17kyVNz2VHeGWeYk9Y+RHNndSlS4AGSG5f011o4IBNDCCATAwCwYDVR0PBAQDAgbAMBMGA1UdJQQMMAoGCCsGAQUFBwMEMCkGA1UdDgQiBCAJ2M58r0PpLf5srxAlpkVzR+/Fc3veDPGdrhpRNcVQoDCB4AYDVR0jBIHYMIHVgCDl/hEG/NoIECAlZLNNwepXGQm7dWgpwThW1yukL72iGqGBjqSBizCBiDFBMD8GA1UEAxM4U3RhdGUgU2VjdXJpdHkgU2VydmljZSBvZiBSZXB1YmxpYyBLYXpha2hzdGFuIFByaW1hcnkgQ0ExNjA0BgNVBAoTLVN0YXRlIFNlY3VyaXR5IFNlcnZpY2Ugb2YgUmVwdWJsaWMgS2F6YWtoc3RhbjELMAkGA1UEBhMCS1qCIOX+EQb82ggQICVks03B6lcZCbt1aCnBOFbXK6QvvaIaMA4GCisGAQQBtREBAgcFAAOBgQCNDfIwRCyBcUe0CrHJZCF4sweFwdkxeyMJlr1n4EMfeWpWtUP1d7DHRATavcgdDhQozhTI/flKdxwbhVsNIC0iNd5n4QTojhBWHfU1EhuzotVpDWo5ezePC5W5x676HQAxTVoafq2lDqI9Mf/NqjC+OHaYmISfHxXDcCHtugPDvQ==';
};

export { getCertificate };
